### ISSUE TITLE
Question about Figure3C

### ISSUE THREAD

**Issue by HopeStar2018** [cavei/MOSClip#2]
Hi,
We are very interested in MOSClip.
We don't understand enough **Figure 3C** in the paper. 
Please help us to clarify the following questions in regard to the radial plot and the pathways.Some of which we cannot extract the meaning of certain pathways and their designated design,

1. What is the significance of the thin lines in regards to the thickers lines?
2. The meaning of the dot plotted in the metabolism pathway.
3. The pathway directly on the curvature of the radial plot, for exaplme the red pathway (exp) and the purple pathway (exp;mut). Is there a significant meaning on the location of the pathways on the curved line of radial plot?
4. The blue pathway (mut) seems to deviate from the rest. Please help us understand why it has doubled back to the center origin?

We would appreciate some tips to better understand the meaning of plotted pathways. Please give me a reply in regard to the questions posted above. Thank you and have a wonderful day.

**Comment by cavei** [comment]
Hi,
thank you for your interest.
1. The line-plot with polar coords has been adapted from ggplot2. The thin lines only connect the first and the last point of each class. They are used to compute the area wrapped by the curve but they do not have any meaning for this analysis.
2. The single dot for the class "cnv;exp;mut" means that there is only one pathway (the Metabolism pathway) that is shared across CNV, expression and Mutation.
3. We have plot the radial plot according to the alphabetical order of the classes (clock-wise).
4. The mutation line comes back to the center because two or more pathway categories have count 1. In fact, the center value correspond to 1. Looking at the data we have
  Cell Cycle  1
  Digestion and absorption  1
  Disease  2
  Gene expression (Transcription)  1
  The line mutation stays in 1 for Cell Cycle and Digestion and absorption, than move to disease in 2 and comes back to 1 for Gene expression.

This plot is meant to have a global overview of how the omics cooperate in the pathways.
To go deeper in the value of each category you should use the object freqDataFrame that we create in the tutorial
(see section Frequency plot https://cavei.github.io/MOSClipTutorials/workflowGitHub_TCGA_MOSClipAnalysisTutorial.html).

Hope this helps.

Cheers.
