### ISSUE TITLE
Question about Figure3A (met3k3 or met2k2)

### ISSUE THREAD

**Issue by HopeStar2018** [cavei/MOSClip#3]
Hi,
We are your funs and we are very interested in MOSClip.
We don't understand enough Figure 3A in the paper.
** We will not explain what is meant by met2k2 or met3k3. **
Thank you and have a wonderful day.

**Comment by cavei** [comment]
Hi, first of all thanks for you interest!
In figure 3, the column met3k3 means that the p-values of the column are computed for the class=3 of methylation that has been summarized in three category. When you summarize the gene methylation with clusters, you can specify a range of cluster number to test (in our fig3 min 2 and max 3). The best separation according to the silhouette index is chosen. For "Interleukin-35 signalling" the best separation of methylation is in two classes, met2k2, the last number 2 means that we are testing for different survival class=2 vs class=1.
For "PTEN regulation" we find that the optimal is summarize methylation in three classes (met3k): this means that we can test the survival association of class=2 vs class=1 (met3k2) and the association between class=3 vs class=1 (met3k3).

Hope this help. Otherwise do not hesitate to write me again.
