### ISSUE TITLE
Regarding input your own gene list for computing survival instead of using graphite

### ISSUE THREAD

**Issue by SmritiChawla** [cavei/MOSClip#4]
Hi, thanks for the tool. Is there an option to input your own gene list instead of using pathways from garphite.

Thanks

**Comment by cavei** [comment]
Hi,
Yes you can.
I will create a short tutorial in next few days.

**Comment by cavei** [comment]
Hi,
I have created a new short tutorial to perform analysis of gene list rather than pathways.

You can find it among [tutorials](https://cavei.github.io/MOSClipTutorials/) in the section "Special features Tutorials"
[how to perform the analysis with gene sets rather than pathways](https://cavei.github.io/MOSClipTutorials/workflowGitHub_TCGA_MOSClipAnalysisTutorial_geneList.html)

In a nutshell you would need to call the pathway analysis (module analysis is not available without topology) with 
argument graph that is a character vector of your favourite genes:

Let multiOmics be the multiOmic object, gene_list the gene set and  survAnnot the survival annotation.
You can perform the analysis as follows:

multiOmicsSurvivalPathwayTest(multiOmics, gene_list, survAnnot)

Hope this help.

Thanks

**Comment by SmritiChawla** [comment]
Thank you so much
